version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: memo_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: memo_database
    volumes:
      - mongo_data:/data/db
    networks:
      - memo_network

volumes:
  mongo_data:

networks:
  memo_network:
